# Generated by Django 4.0.3 on 2022-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('category', models.TextField(verbose_name='Категории')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('symbol', models.CharField(max_length=20, verbose_name='В чем измеряется')),
            ],
        ),
    ]
