# Generated by Django 4.0.3 on 2022-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.JSONField(default=None, verbose_name=[{'ShopsName': models.TextField(verbose_name='Название')}]),
            preserve_default=False,
        ),
    ]
