# Generated by Django 4.0.3 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopsName', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
    ]
