# Generated by Django 4.0.3 on 2022-03-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_shops_remove_product_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productApp.shops'),
            preserve_default=False,
        ),
    ]
