# Generated by Django 4.0.3 on 2022-03-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_product_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productApp.shops'),
        ),
    ]
