# Generated by Django 4.0.3 on 2022-03-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_alter_product_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='ShopsNfffame',
            field=models.TextField(default=None, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productApp.shops'),
        ),
    ]
