# Generated by Django 4.0.3 on 2022-03-26 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_remove_product_shops_product_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
            preserve_default=False,
        ),
    ]
